@startuml
'https://plantuml.com/class-diagram

class ParseDataFile
{

       String: OutputStringBody, OutputStringHeader
       FILE: Input42

       Run Program

       void printTable(String Header, String Body)

}

class ParseFile{

      Scanner FileReader

      Constructor ParseFile(Scanner)

      readFile(){return PersonList}

      String makeBodyString() {return BodyString}

      String getHeader() {return HeaderString}

}

class Person
{
    String: FirstName, LastName, Salary

    Constructor Person(FirstName, LastName, Salary)

    getFirstName()

    getLastName()

    getNumber()
}

ParseDataFile<--ParseFile

ParseFile<-Person
ParseDataFile<-Person


@enduml