@startuml
'https://plantuml.com/class-diagram

class NameSorter{

       String: Statement1, Statement2

       FILE: input, output

       run program

       getNames()

       FilePrint()

}

class OutputBuilder{

        makeNameHeader(List<String>){return String}

        makeNameBody(List<String>){return String}
}

OutputBuilder-->NameSorter

@enduml