@startuml
'https://plantuml.com/class-diagram

class NameSorter{

       String: Statement1, Statement2

       FILE: input, output

       run program

       (List<String>) readFileInput()

       PrintOutputString()

}

class OutputBuilder{

        makeNameHeader(int size){return String}

        makeNameBody(List<String>){return String}
}

OutputBuilder-->NameSorter

@enduml